### ISSUE TITLE
WebAssembly.instantiate(): expected magic word error

### ISSUE THREAD

**Issue by skobak** [splinetool/react-spline#134]
Hi!

After certain point in time I start getting the following error:

```
ERROR
Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 43 61 6e 6e @+0). Build with -s ASSERTIONS=1 for more info.
RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 43 61 6e 6e @+0). Build with -s ASSERTIONS=1 for more info.
    at abort (http://localhost:3000/static/js/vendors-node_modules_splinetool_runtime_build_process_js.chunk.js:449:15)
    at http://localhost:3000/static/js/vendors-node_modules_splinetool_runtime_build_process_js.chunk.js:519:11
```

It's working good on simple model, but when I add object it's breaks.

Here is 
[codesandbox](https://codesandbox.io/p/sandbox/k7w3pz?file=%2Fsrc%2FApp.jsx%3A1%2C1)

Do you have any ideas?

**Comment by skobak** [comment]
Not sure that is relevant, but I just updated to

` "@splinetool/runtime": "^0.9.364",`

and seems like problem disappears .
Am I right that the new version have a fix?
