### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'A')

### ISSUE THREAD

**Issue by YevheniiKisel** [splinetool/react-spline#185]
Hello Spline community ❤️ 
Trying to integrate Spline animation into my Next JS (TypeScript strict) project. And getting a TypeError. 

package.json / dependency:
```
"@fortawesome/fontawesome-svg-core": "^6.5.1",
    "@fortawesome/free-solid-svg-icons": "^6.5.1",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@hookform/resolvers": "^3.3.4",
    "@splinetool/react-spline": "^3.0.3",
    "@splinetool/runtime": "^1.4.5",
    "@vercel/analytics": "^1.2.2",
    "googleapis": "^134.0.0",
    "next": "14.1.4",
    "react": "^18",
    "react-dom": "^18",
    "react-hook-form": "^7.51.1",
    "yup": "^1.4.0"
```

HeroSection:
```
"use client"
import { Button, HeroTitle } from '@components/_common/atoms';
import Spline from '@splinetool/react-spline';
import styles from './HeroSection.module.scss';

const status = 'Automated Yard';
const title = 'Automate your Trailer Yard with AI';
const info = 'Check in and check out in seconds!';

export const HeroSection = () => (
  <section className={styles.container}>
      <div className={styles.section}>
        <HeroTitle info={info} title={title} status={status} />
        <Button label="Configure Now" />
      </div>
      <div>
        <Spline scene="https://prod.spline.design/6Wq1Q7YGyM-iab9i/scene.splinecode" />
      </div>
    </section>

)
```

Console: 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'A')
    at ue (react-spline.js:371:27)
    at xe (react-spline.js:493:44)
    at Object.or [as jsx] (react-spline.js:447:24)
    at eval (react-spline.js:778:28)
    at renderWithHooks (react-dom.development.js:11021:18)
    at updateForwardRef (react-dom.development.js:15686:20)
    at mountLazyComponent (react-dom.development.js:16687:17)
    at beginWork$1 (react-dom.development.js:18388:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20498:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20547:16)
    at invokeGuardedCallback (react-dom.development.js:20622:29)
    at beginWork (react-dom.development.js:26813:7)
    at performUnitOfWork (react-dom.development.js:25637:12)
    at workLoopSync (react-dom.development.js:25353:5)
    at renderRootSync (react-dom.development.js:25308:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:24432:74)
    at workLoop (scheduler.development.js:256:34)
    at flushWork (scheduler.development.js:225:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:534:21)
```

**Comment by ayibovShakhzod** [comment]
To resolve the "TypeError: Cannot read properties of undefined (reading 'A')" issue in your Next.js project, update your dependencies to the following versions:
`"@splinetool/react-spline": "^2.2.6",
"@splinetool/runtime": "^1.4.5"`

These versions contain fixes that should address the error you're encountering. Make sure to update your package.json and run npm install or yarn install to apply the changes.

**Comment by NicolasLEBEAU** [comment]
Thanks ! Issue resolved for me

**Comment by YevheniiKisel** [comment]
@ayibovShakhzod Thank you very much for your quick response. You helped me a lot! 
Issue has been resolved
