### ISSUE TITLE
IMPORTANT - Rendering Error in react-spline with Certain Scenes

### ISSUE THREAD

**Issue by pietrociatta** [splinetool/react-spline#208]
Description: Since this morning, I, along with other users, have encountered a rendering issue when using react-spline with certain scenes, including the one linked below.

Url: https://app.spline.design/community/file/09a1967a-051f-4493-b214-9a87e7e53aec

Additionally, this issue occurs on the Spline.design website itself, where the scene fails to render correctly. This problem seems to affect only the Brave and Chrome browsers. The scene renders as expected in Safari.

LOG:
```
entry-server-routing.7a9d563f.js:3087 Uncaught (in promise) TypeError: Failed to execute 'uniform1fv' on 'WebGL2RenderingContext': The provided float value is non-finite.
    at _me.ime [as setValue] (entry-server-routing.7a9d563f.js:3087:12555)
    at Xb.upload (entry-server-routing.7a9d563f.js:3087:15800)
    at eo (entry-server-routing.7a9d563f.js:3145:78041)
    at JN.renderBufferDirect (entry-server-routing.7a9d563f.js:3145:66287)
    at ti (entry-server-routing.7a9d563f.js:3145:72211)
    at Ar (entry-server-routing.7a9d563f.js:3145:71747)
    at cr (entry-server-routing.7a9d563f.js:3145:70881)
    at JN.render (entry-server-routing.7a9d563f.js:3145:69380)
    at OpaquePass.render (pages_index.910bd624.js:2627:878)
    at MRTEffectComposer.render (pages_index.910bd624.js:2627:6334)
    at Post.render (pages_index.910bd624.js:2781:8104)
    at SplineRenderer.renderSplineScene (pages_index.910bd624.js:3187:7827)
    at rR.renderSingle (chunk-0428ada7.js:338:2143)
    at rR._renderFrames (chunk-0428ada7.js:338:8211)
    at rR.render (chunk-0428ada7.js:338:8060)
    at lQ.render (chunk-0428ada7.js:374:72221)
    at lQ.animate (chunk-0428ada7.js:374:67489)
    at lQ.start (chunk-0428ada7.js:374:71737)
    at lQ.setScene (chunk-0428ada7.js:374:72381)
    at Sj (chunk-0428ada7.js:374:75672)
    at chunk-0428ada7.js:882:62013
```

**Comment by LAWTED** [comment]
I upgrade @splinetool/runtime to 1.9.21 then it fixed
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/e0d955d6-38fa-4a6f-b704-cebd6d078c09">
